libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
  
runtime: python27
api_version: 1
threadsafe: true

handlers:
  
- url: /
  static_files: sample2.html
  upload: sample2.html
  
- url: /home
  script: main.app
