runtime: php73

handlers:
- url: /home
  static_files: form02.html
  upload: form02.html

- url: /
  static_files: sample2.html
  upload: sample2.html
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
